export type LanguageCode = "en" | "hi" | "mr" | "gu" | "ta" | "te" | "kn" | "bn";

export type LanguagePack = {
  nav: { ask: string; ai: string; screening: string; regulatory: string; comparison: string; sources: string; reports: string; dashboard: string; how: string; about: string };
  chat: { greeting: string; suggested: string; help: string; preliminary: string; executive: string; findings: string; nextSteps: string; sources: string; disclaimer: string; why: string; demo: string; responseLanguage: string; originalLanguage: string };
  stages: string[];
  suggestions: string[];
};

const en: LanguagePack = {
  nav: { ask: "Ask Sahayak", ai: "AI Sahayak", screening: "IP Screening", regulatory: "Regulatory Navigator", comparison: "Country Comparison", sources: "Knowledge Sources", reports: "Reports", dashboard: "Dashboard", how: "How It Works", about: "About / Impact" },
  chat: { greeting: "Namaste. I’m Sahayak — ready to help you navigate Ayurveda IP and regulatory research.", suggested: "Suggested questions", help: "WHAT CAN I HELP YOU WITH?", preliminary: "PRELIMINARY AI-ASSISTED GUIDANCE", executive: "EXECUTIVE SUMMARY", findings: "KEY FINDINGS", nextSteps: "RECOMMENDED NEXT STEPS", sources: "SOURCES & EVIDENCE", disclaimer: "AI-assisted preliminary guidance only. Verify information with qualified patent, legal and regulatory professionals.", why: "Why this answer?", demo: "DEMO MODE", responseLanguage: "RESPONSE LANGUAGE", originalLanguage: "ORIGINAL SOURCE LANGUAGE" },
  stages: ["Understanding your question…", "Retrieving relevant knowledge…", "Ranking evidence…", "Mapping citations…", "Generating preliminary answer…"],
  suggestions: ["Can I patent this Ayurvedic formulation?", "Does TKDL affect patentability?", "What regulatory pathway may apply to my product?", "What should I consider before exporting to the US?", "Compare India and EU requirements.", "How can I protect an Ayurveda-based product internationally?"]
};

const packs: Record<LanguageCode, LanguagePack> = {
  en,
  hi: { nav: { ask: "सहायक से पूछें", ai: "एआई सहायक", screening: "आईपी स्क्रीनिंग", regulatory: "नियामक नेविगेटर", comparison: "देश तुलना", sources: "ज्ञान स्रोत", reports: "रिपोर्ट", dashboard: "डैशबोर्ड", how: "यह कैसे काम करता है", about: "परिचय / प्रभाव" }, chat: { greeting: "नमस्ते। मैं सहायक हूँ — आयुर्वेद IP और नियामक अनुसंधान को समझने में आपकी मदद करने के लिए तैयार हूँ।", suggested: "सुझाए गए प्रश्न", help: "मैं आपकी किस तरह मदद कर सकता हूँ?", preliminary: "प्रारंभिक एआई-सहायित मार्गदर्शन", executive: "कार्यकारी सारांश", findings: "मुख्य निष्कर्ष", nextSteps: "अनुशंसित अगले कदम", sources: "स्रोत और साक्ष्य", disclaimer: "केवल एआई-सहायित प्रारंभिक मार्गदर्शन। निर्णय लेने से पहले योग्य पेटेंट, कानूनी और नियामक विशेषज्ञों से सत्यापन करें।", why: "यह उत्तर क्यों?", demo: "डेमो मोड", responseLanguage: "उत्तर की भाषा", originalLanguage: "मूल स्रोत भाषा" }, stages: ["आपके प्रश्न को समझना…", "प्रासंगिक ज्ञान खोजना…", "साक्ष्य को क्रम देना…", "उद्धरण मैप करना…", "प्रारंभिक उत्तर बनाना…"], suggestions: ["क्या मैं इस आयुर्वेदिक फॉर्मूलेशन का पेटेंट करा सकता हूँ?", "क्या TKDL पेटेंट योग्यता को प्रभावित करता है?", "मेरे उत्पाद के लिए कौन-सा नियामक मार्ग लागू हो सकता है?", "USA में निर्यात करने से पहले मुझे किन बातों पर विचार करना चाहिए?", "भारत और EU की आवश्यकताओं की तुलना करें।", "मैं आयुर्वेद-आधारित उत्पाद की अंतरराष्ट्रीय सुरक्षा कैसे कर सकता हूँ?"] },
  mr: { nav: { ask: "सहायकला विचारा", ai: "एआय सहायक", screening: "आयपी स्क्रीनिंग", regulatory: "नियामक नेव्हिगेटर", comparison: "देश तुलना", sources: "ज्ञान स्रोत", reports: "अहवाल", dashboard: "डॅशबोर्ड", how: "हे कसे कार्य करते", about: "परिचय / प्रभाव" }, chat: { greeting: "नमस्कार. मी सहायक आहे — आयुर्वेद IP आणि नियामक संशोधन समजून घेण्यासाठी मदत करण्यास तयार आहे.", suggested: "सुचवलेले प्रश्न", help: "मी तुम्हाला कशी मदत करू शकतो?", preliminary: "प्राथमिक एआय-सहाय्यित मार्गदर्शन", executive: "कार्यकारी सारांश", findings: "मुख्य निष्कर्ष", nextSteps: "शिफारस केलेली पुढील पावले", sources: "स्रोत आणि पुरावे", disclaimer: "हे केवळ एआय-सहाय्यित प्राथमिक मार्गदर्शन आहे. निर्णयापूर्वी पात्र पेटंट, कायदेशीर आणि नियामक तज्ज्ञांकडून पडताळणी करा.", why: "हे उत्तर का?", demo: "डेमो मोड", responseLanguage: "उत्तराची भाषा", originalLanguage: "मूळ स्रोत भाषा" }, stages: ["तुमचा प्रश्न समजून घेत आहे…", "संबंधित ज्ञान शोधत आहे…", "पुराव्यांना क्रम देत आहे…", "उद्धरणे जोडत आहे…", "प्राथमिक उत्तर तयार करत आहे…"], suggestions: ["मी या आयुर्वेदिक फॉर्म्युलेशनचे पेटंट घेऊ शकतो का?", "TKDL पेटंटयोग्यतेवर परिणाम करते का?", "माझ्या उत्पादनासाठी कोणता नियामक मार्ग लागू होऊ शकतो?", "अमेरिकेत निर्यात करण्यापूर्वी कोणत्या बाबी तपासाव्यात?", "भारत आणि EU आवश्यकतांची तुलना करा.", "आयुर्वेद-आधारित उत्पादनाचे आंतरराष्ट्रीय संरक्षण कसे करावे?"] },
  gu: { nav: { ask: "સહાયકને પૂછો", ai: "એઆઈ સહાયક", screening: "આઈપી સ્ક્રીનિંગ", regulatory: "નિયમનકારી નેવિગેટર", comparison: "દેશ સરખામણી", sources: "જ્ઞાન સ્ત્રોતો", reports: "અહેવાલો", dashboard: "ડેશબોર્ડ", how: "આ કેવી રીતે કાર્ય કરે છે", about: "પરિચય / અસર" }, chat: { greeting: "નમસ્તે. હું સહાયક છું — આયુર્વેદ IP અને નિયમનકારી સંશોધનમાં માર્ગદર્શન આપવા તૈયાર છું.", suggested: "સૂચવાયેલા પ્રશ્નો", help: "હું તમને કેવી રીતે મદદ કરી શકું?", preliminary: "પ્રાથમિક AI-સહાયિત માર્ગદર્શન", executive: "કાર્યકારી સારાંશ", findings: "મુખ્ય તારણો", nextSteps: "ભલામણ કરેલા આગળના પગલાં", sources: "સ્ત્રોતો અને પુરાવા", disclaimer: "આ માત્ર AI-સહાયિત પ્રાથમિક માર્ગદર્શન છે. નિર્ણય પહેલાં યોગ્ય પેટન્ટ, કાનૂની અને નિયમનકારી નિષ્ણાતો પાસેથી ચકાસણી કરો.", why: "આ જવાબ શા માટે?", demo: "ડેમો મોડ", responseLanguage: "જવાબની ભાષા", originalLanguage: "મૂળ સ્ત્રોત ભાષા" }, stages: ["તમારો પ્રશ્ન સમજી રહ્યા છીએ…", "સંબંધિત જ્ઞાન શોધી રહ્યા છીએ…", "પુરાવાને ક્રમ આપી રહ્યા છીએ…", "સંદર્ભો મેપ કરી રહ્યા છીએ…", "પ્રાથમિક જવાબ બનાવી રહ્યા છીએ…"], suggestions: ["શું હું આ આયુર્વેદિક ફોર્મ્યુલેશન માટે પેટન્ટ મેળવી શકું?", "શું TKDL પેટન્ટ યોગ્યતાને અસર કરે છે?", "મારા ઉત્પાદન માટે કયો નિયમનકારી માર્ગ લાગુ પડી શકે?", "USAમાં નિકાસ પહેલાં કઈ બાબતો ધ્યાનમાં લેવી?", "ભારત અને EUની જરૂરિયાતોની સરખામણી કરો.", "આયુર્વેદ આધારિત ઉત્પાદનનું આંતરરાષ્ટ્રીય રક્ષણ કેવી રીતે કરવું?"] },
  ta: { nav: { ask: "சஹாயக்கிடம் கேளுங்கள்", ai: "AI சஹாயக்", screening: "IP பரிசோதனை", regulatory: "ஒழுங்குமுறை வழிகாட்டி", comparison: "நாடுகள் ஒப்பீடு", sources: "அறிவு ஆதாரங்கள்", reports: "அறிக்கைகள்", dashboard: "டாஷ்போர்டு", how: "இது எப்படி செயல்படுகிறது", about: "அறிமுகம் / தாக்கம்" }, chat: { greeting: "வணக்கம். நான் சஹாயக் — ஆயுர்வேத IP மற்றும் ஒழுங்குமுறை ஆய்வில் வழிகாட்டத் தயாராக உள்ளேன்.", suggested: "பரிந்துரைக்கப்பட்ட கேள்விகள்", help: "நான் எவ்வாறு உதவலாம்?", preliminary: "முதற்கட்ட AI உதவிய வழிகாட்டுதல்", executive: "நிர்வாகச் சுருக்கம்", findings: "முக்கிய கண்டறிதல்கள்", nextSteps: "பரிந்துரைக்கப்பட்ட அடுத்த படிகள்", sources: "ஆதாரங்கள் மற்றும் சான்றுகள்", disclaimer: "இது AI உதவிய முதற்கட்ட வழிகாட்டுதல் மட்டுமே. முடிவெடுப்பதற்கு முன் தகுதியான காப்புரிமை, சட்ட மற்றும் ஒழுங்குமுறை நிபுணர்களிடம் சரிபார்க்கவும்.", why: "இந்த பதில் ஏன்?", demo: "டெமோ பயன்முறை", responseLanguage: "பதில் மொழி", originalLanguage: "மூல ஆதார மொழி" }, stages: ["உங்கள் கேள்வியைப் புரிந்துகொள்கிறோம்…", "தொடர்புடைய அறிவைத் தேடுகிறோம்…", "சான்றுகளை வரிசைப்படுத்துகிறோம்…", "மேற்கோள்களை இணைக்கிறோம்…", "முதற்கட்ட பதிலை உருவாக்குகிறோம்…"], suggestions: ["இந்த ஆயுர்வேத தயாரிப்புக்கு காப்புரிமை பெற முடியுமா?", "TKDL காப்புரிமைத் தகுதியை பாதிக்குமா?", "எந்த ஒழுங்குமுறை பாதை பொருந்தும்?", "USAக்கு ஏற்றுமதி முன் என்ன கருத்தில் கொள்ள வேண்டும்?", "இந்தியா மற்றும் EU தேவைகளை ஒப்பிடுங்கள்.", "ஆயுர்வேத தயாரிப்பை சர்வதேச அளவில் பாதுகாப்பது எப்படி?"] },
  te: { nav: { ask: "సహాయక్‌ను అడగండి", ai: "AI సహాయక్", screening: "IP స్క్రీనింగ్", regulatory: "నియంత్రణ నావిగేటర్", comparison: "దేశాల పోలిక", sources: "జ్ఞాన వనరులు", reports: "నివేదికలు", dashboard: "డాష్‌బోర్డ్", how: "ఇది ఎలా పనిచేస్తుంది", about: "గురించి / ప్రభావం" }, chat: { greeting: "నమస్తే. నేను సహాయక్ — ఆయుర్వేద IP మరియు నియంత్రణ పరిశోధనలో మార్గనిర్దేశం చేయడానికి సిద్ధంగా ఉన్నాను.", suggested: "సూచించిన ప్రశ్నలు", help: "నేను ఎలా సహాయపడగలను?", preliminary: "ప్రాథమిక AI సహాయక మార్గదర్శకం", executive: "కార్యనిర్వాహక సారాంశం", findings: "ముఖ్య ఫలితాలు", nextSteps: "సిఫార్సు చేసిన తదుపరి దశలు", sources: "వనరులు మరియు సాక్ష్యాలు", disclaimer: "ఇది AI సహాయక ప్రాథమిక మార్గదర్శకం మాత్రమే. నిర్ణయాల ముందు అర్హత కలిగిన పేటెంట్, చట్టపరమైన మరియు నియంత్రణ నిపుణులతో ధృవీకరించండి.", why: "ఈ సమాధానం ఎందుకు?", demo: "డెమో మోడ్", responseLanguage: "సమాధాన భాష", originalLanguage: "మూల వనరు భాష" }, stages: ["మీ ప్రశ్నను అర్థం చేసుకుంటున్నాం…", "సంబంధిత జ్ఞానాన్ని వెతుకుతున్నాం…", "సాక్ష్యాలను ర్యాంక్ చేస్తున్నాం…", "సైటేషన్లను మ్యాప్ చేస్తున్నాం…", "ప్రాథమిక సమాధానాన్ని రూపొందిస్తున్నాం…"], suggestions: ["ఈ ఆయుర్వేద ఫార్ములేషన్‌కు పేటెంట్ పొందగలనా?", "TKDL పేటెంట్ అర్హతను ప్రభావితం చేస్తుందా?", "నా ఉత్పత్తికి ఏ నియంత్రణ మార్గం వర్తిస్తుంది?", "USAకి ఎగుమతి ముందు ఏమి పరిగణించాలి?", "భారతదేశం మరియు EU అవసరాలను పోల్చండి.", "ఆయుర్వేద ఉత్పత్తిని అంతర్జాతీయంగా ఎలా రక్షించాలి?"] },
  kn: { nav: { ask: "ಸಹಾಯಕನನ್ನು ಕೇಳಿ", ai: "AI ಸಹಾಯಕ", screening: "IP ಸ್ಕ್ರೀನಿಂಗ್", regulatory: "ನಿಯಂತ್ರಣ ನ್ಯಾವಿಗೇಟರ್", comparison: "ದೇಶ ಹೋಲಿಕೆ", sources: "ಜ್ಞಾನ ಮೂಲಗಳು", reports: "ವರದಿಗಳು", dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", how: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", about: "ಪರಿಚಯ / ಪರಿಣಾಮ" }, chat: { greeting: "ನಮಸ್ಕಾರ. ನಾನು ಸಹಾಯಕ — ಆಯುರ್ವೇದ IP ಮತ್ತು ನಿಯಂತ್ರಣ ಸಂಶೋಧನೆಯಲ್ಲಿ ಮಾರ್ಗದರ್ಶನ ನೀಡಲು ಸಿದ್ಧನಿದ್ದೇನೆ.", suggested: "ಸೂಚಿಸಿದ ಪ್ರಶ್ನೆಗಳು", help: "ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?", preliminary: "ಪ್ರಾಥಮಿಕ AI-ಸಹಾಯಿತ ಮಾರ್ಗದರ್ಶನ", executive: "ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ", findings: "ಪ್ರಮುಖ ಕಂಡುಹಿಡಿಕೆಗಳು", nextSteps: "ಶಿಫಾರಸು ಮಾಡಿದ ಮುಂದಿನ ಹಂತಗಳು", sources: "ಮೂಲಗಳು ಮತ್ತು ಸಾಕ್ಷ್ಯ", disclaimer: "ಇದು AI-ಸಹಾಯಿತ ಪ್ರಾಥಮಿಕ ಮಾರ್ಗದರ್ಶನ ಮಾತ್ರ. ನಿರ್ಧಾರಗಳ ಮೊದಲು ಅರ್ಹ ಪೇಟೆಂಟ್, ಕಾನೂನು ಮತ್ತು ನಿಯಂತ್ರಣ ತಜ್ಞರಿಂದ ಪರಿಶೀಲಿಸಿ.", why: "ಈ ಉತ್ತರ ಏಕೆ?", demo: "ಡೆಮೋ ಮೋಡ್", responseLanguage: "ಉತ್ತರದ ಭಾಷೆ", originalLanguage: "ಮೂಲ ಮೂಲದ ಭಾಷೆ" }, stages: ["ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ…", "ಸಂಬಂಧಿತ ಜ್ಞಾನ ಹುಡುಕುತ್ತಿದ್ದೇವೆ…", "ಸಾಕ್ಷ್ಯವನ್ನು ಕ್ರಮಗೊಳಿಸುತ್ತಿದ್ದೇವೆ…", "ಉಲ್ಲೇಖಗಳನ್ನು ಜೋಡಿಸುತ್ತಿದ್ದೇವೆ…", "ಪ್ರಾಥಮಿಕ ಉತ್ತರ ರಚಿಸುತ್ತಿದ್ದೇವೆ…"], suggestions: ["ಈ ಆಯುರ್ವೇದ ಫಾರ್ಮುಲೇಶನ್‌ಗೆ ಪೇಟೆಂಟ್ ಪಡೆಯಬಹುದೇ?", "TKDL ಪೇಟೆಂಟ್ ಅರ್ಹತೆಯ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆಯೇ?", "ನನ್ನ ಉತ್ಪನ್ನಕ್ಕೆ ಯಾವ ನಿಯಂತ್ರಣ ಮಾರ್ಗ ಅನ್ವಯಿಸುತ್ತದೆ?", "USAಗೆ ರಫ್ತು ಮಾಡುವ ಮೊದಲು ಏನು ಪರಿಗಣಿಸಬೇಕು?", "ಭಾರತ ಮತ್ತು EU ಅವಶ್ಯಕತೆಗಳನ್ನು ಹೋಲಿಸಿ.", "ಆಯುರ್ವೇದ ಉತ್ಪನ್ನವನ್ನು ಅಂತರರಾಷ್ಟ್ರೀಯವಾಗಿ ಹೇಗೆ ರಕ್ಷಿಸುವುದು?"] },
  bn: { nav: { ask: "সহায়ককে জিজ্ঞেস করুন", ai: "এআই সহায়ক", screening: "আইপি স্ক্রিনিং", regulatory: "নিয়ন্ত্রক ন্যাভিগেটর", comparison: "দেশ তুলনা", sources: "জ্ঞান উৎস", reports: "রিপোর্ট", dashboard: "ড্যাশবোর্ড", how: "এটি কীভাবে কাজ করে", about: "সম্পর্কে / প্রভাব" }, chat: { greeting: "নমস্কার। আমি সহায়ক — আয়ুর্বেদ IP ও নিয়ন্ত্রক গবেষণায় আপনাকে পথ দেখাতে প্রস্তুত।", suggested: "প্রস্তাবিত প্রশ্ন", help: "আমি কীভাবে সাহায্য করতে পারি?", preliminary: "প্রাথমিক AI-সহায়িত নির্দেশনা", executive: "নির্বাহী সারাংশ", findings: "মূল অনুসন্ধান", nextSteps: "প্রস্তাবিত পরবর্তী পদক্ষেপ", sources: "উৎস ও প্রমাণ", disclaimer: "এটি কেবল AI-সহায়িত প্রাথমিক নির্দেশনা। সিদ্ধান্তের আগে যোগ্য পেটেন্ট, আইন ও নিয়ন্ত্রক বিশেষজ্ঞদের মাধ্যমে যাচাই করুন।", why: "এই উত্তর কেন?", demo: "ডেমো মোড", responseLanguage: "উত্তরের ভাষা", originalLanguage: "মূল উৎসের ভাষা" }, stages: ["আপনার প্রশ্ন বুঝছি…", "প্রাসঙ্গিক জ্ঞান খুঁজছি…", "প্রমাণের ক্রম নির্ধারণ করছি…", "উদ্ধৃতি ম্যাপ করছি…", "প্রাথমিক উত্তর তৈরি করছি…"], suggestions: ["আমি কি এই আয়ুর্বেদিক ফর্মুলেশনের পেটেন্ট করতে পারি?", "TKDL কি পেটেন্টযোগ্যতাকে প্রভাবিত করে?", "আমার পণ্যের জন্য কোন নিয়ন্ত্রক পথ প্রযোজ্য?", "USA-তে রপ্তানির আগে কী বিবেচনা করব?", "ভারত ও EU-এর প্রয়োজনীয়তা তুলনা করুন।", "আয়ুর্বেদ-ভিত্তিক পণ্য আন্তর্জাতিকভাবে কীভাবে সুরক্ষিত করব?"] }
};

export const getLanguagePack = (language: LanguageCode) => packs[language] || en;
export const languageMatrix = Object.keys(packs) as LanguageCode[];
